import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

@Schema()
export class Payment extends Document {
  @Prop()
  Agent_id: string;

  @Prop()
  Agent_name:string;

  @Prop({unique: true })
  subscriptionid: string; // Autogenerated subscription ID

  @Prop()
  planName: string;

  @Prop({type: Number })
  amount: number;

  @Prop({default: Date.now })
  Date: Date; // Set to current date when the payment is created

  @Prop({default: Date.now })
  Time: Date; // Set to current time when the payment is created

  @Prop({default: 30})
  HowManyDaysPlan: number; // Set to current time when the payment is created

  @Prop({default: 30})
  DateOfExpiration: Date; // Set to current time when the payment is created
  
  
  @Prop({default: "Valid" })
  ExpirationStatus: string;
}

export const PaymentSchema = SchemaFactory.createForClass(Payment);
